language: node_js
node_js: stable
cache: npm

install:
  - npm ci

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
